apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-demo
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: "docker.io/abondar/knativedemo:1.1-SNAPSHOT"
          ports:
            - containerPort: 8080
